version: "3.9"

services:
  # База данных PostgreSQL
  cyberedu_db:
    image: postgres:15
    container_name: cyberedu_db
    environment:
      POSTGRES_DB: "cyberEdu"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1"
    networks:
      - cyberedu-network
    ports:
      - "5456:5432"
    volumes:
      - postgres-cyberedu-data:/var/lib/postgresql/data

  # Бекенд сервис (Spring Boot)
  cyberedu-backend:
    build:
      context: ./backend
    container_name: cyberedu-backend
    environment:
      SERVER_PORT: 8080
      JWT_SECRET_KEY: "s7k5n2x9r1v6y8w4z7u5i3o9l2p5n0x3r1v6y8w4z7u5i3o9l2p5n0x3"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://cyberedu_db:5432/cyberEdu"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "1"
    ports:
      - "8080:8080"
    depends_on:
      - cyberedu_db
    networks:
      - cyberedu-network

  # ML сервис (FastAPI)
  fastapi-app:
    build:
      context: ./ml
    container_name: cyberedu-scenario-api
    ports:
      - "8000:8000"
    volumes:
      - ./ml/ai/json_dumps:/app/ai/json_dumps
      - ./ml/logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    networks:
      - cyberedu-network

networks:
  cyberedu-network:
    driver: bridge

volumes:
  postgres-cyberedu-data: